nervina-labs/nft-wallet

- src/constants/env.ts
> fix: Remove oss img host

- src/components/Card/CardImage.tsx
- src/components/Holder/index.tsx
- src/components/HolderAvatar/index.tsx
- src/models/user.ts
- src/utils/index.ts
- src/views/NFT/index.tsx
- src/views/NFTs/User.tsx
- src/views/Profile/ImagePreview.tsx
- src/views/Profile/index.tsx
> feat: Add tid to avatar

- package.json
- yarn.lock
> refactor: add  npm start script

- package.json
- yarn.lock
> chore: npm start

- package.json
- yarn.lock
> merge develop to staging

- src/components/Image/index.tsx
- src/components/ParallaxTilt/index.tsx
- src/utils/dom.ts
- src/views/NFT/index.tsx
- src/views/Shop/index.tsx
> feat: disable preview image context

- yarn.lock
> fix: lock file

- package.json
- src/components/InfiniteList/index.tsx
- yarn.lock
> feat: Add columns

- src/routes/index.tsx
- src/routes/routes.ts
- src/views/PDFViewer/index.tsx
> feat: lazy load pdf viewer

- package.json
- src/components/ActionDialog/index.tsx
- src/components/Button/index.tsx
- src/components/Image/index.tsx
- src/components/Like/index.tsx
- src/components/LoginButton/index.tsx
- src/components/QRcodeScaner/index.tsx
- src/components/Share/index.tsx
- src/views/AddressCollector/index.tsx
- src/views/Claim/index.tsx
- src/views/Help/index.tsx
- src/views/Login/index.tsx
- src/views/Profile/ImagePreview.tsx
- src/views/Profile/index.tsx
- src/views/Transactions/index.tsx
- src/views/Transfer/dasSelector.tsx
- src/views/Transfer/index.tsx
- yarn.lock
> chore: switch material-ui to mibao-ui

- package.json
- src/utils/url.ts
- src/views/Issuer/components/nftCards.tsx
- yarn.lock
> refactor: update mibao-ui version

- src/hooks/useLikeStatus.ts
- src/views/Issuer/components/nftCards.tsx
- src/views/NFTs/card.tsx
> feat: use like hooks

- src/utils/number.ts
- src/views/NFTs/card.tsx
- src/views/NFTs/info.tsx
- src/views/Profile/DrawerAction.tsx
- src/views/Profile/DrawerConfig.tsx
- src/views/Profile/DrawerImage.tsx
- src/views/Profile/ImagePreview.tsx
> fix: profile

- src/views/Collection/index.tsx
- src/views/Issuer/components/issuerInfo.tsx
- src/views/Issuer/hooks/useIssuerInfo.ts
- src/views/NFT/components/renderer.tsx
- src/views/Ranking/index.tsx
> feat: add page not found handle

- src/components/ThreeDPreview/index.tsx
- src/views/NFT/components/renderer.tsx
> rerf: model viewer

- public/index.html
- src/components/OrderDrawer/Reselect.tsx
- src/components/OrderDrawer/SelectPayment.tsx
- src/constants/env.ts
> feat: support wx-h5 payment

- src/constants/env.ts
- src/utils/url.ts
> perf: improve webkit performance

- src/components/Share/components/posters/holder.tsx
- src/components/Share/components/posters/issuer.tsx
- src/components/Share/components/posters/nft.tsx
- src/components/Share/index.tsx
- src/hooks/useHtml2Canvas.ts
- src/hooks/useUrlToBase64.ts
- src/utils/url.ts
- src/views/Explore/components/lite.tsx
- src/views/Issuer/components/appbar.tsx
- src/views/NFTs/components/appbar.tsx
>  perf: optimize share poster speed

- src/App.tsx
- src/views/Explore/components/banner.tsx
- src/views/NFTs/card.tsx
> feat: issuer webp and swiper dot

- src/components/NftSortOrKindList/explore.tsx
- src/views/Explore/components/recommend.tsx
> refactor: replace click with link

- src/i18n/en.json
> feat: i18n for s14

- src/constants/env.ts
- src/hooks/useOrder.ts
> fix: chrome wx h5 payment

- src/views/Issuer/components/address.tsx
- src/views/NFT/components/nftTxLogList.tsx
> fix: fixed issuer id layout

- package.json
- src/views/NFT/components/nftDetail.tsx
- src/views/NFT/components/renderer.tsx
- yarn.lock
* nft detail owned badge should not showing in class page
* preview component
> fix: nft detail

- src/i18n/en.json
- src/views/Apps/index.tsx
> fix: i18n change

- src/views/OrderDetail/index.tsx
- src/views/Orders/OrderCard.tsx
also disable order detail cache in weixin
> fix: style

- src/views/Explore/components/recommend.tsx
> fix: recommend items

- src/apis/ServerWalletAPI.ts
- src/views/Collection/index.tsx
- src/views/NFT/components/nftDetail.tsx
> hotfix: white space and recommend

- src/views/NFT/components/footer.tsx
> chore: temporary disable sell feature

- src/views/NFT/components/footer.tsx
> chore: restore sell feture

- src/views/Explore/components/banner.tsx
> fix: fixed layout aspect ratio

- package.json
- src/views/Collection/index.tsx
- src/views/NFTs/info.tsx
- yarn.lock
> hotfix: fixed collection nft card issuer verified icon

- src/components/Follow/index.tsx
> feat: update follow button style

- src/components/Share/components/posters/nft.tsx
> fix: fixed share poster rounded

- src/views/Issuer/components/nftCards.tsx
> fix: replaced issuer fallback img

- src/views/NFTs/DrawerMenu.tsx
> feat: remove arrow

- src/constants/config.ts
- src/views/Issuer/components/appbar.tsx
- src/views/Issuer/components/nftCards.tsx
- src/views/Profile/DrawerImage.tsx
> feat: update `PER_ITEM_LIMIT` to `20`

- public/index.html
- src/index.css
- src/views/NFT/components/footer.tsx
https://user-images.githubusercontent.com/33676809/141946345-22f59789-5a4e-47fb-bd00-0dbe3f384194.MP4
> fix: add ios bottom safe area

- src/views/Explore/components/heading.tsx
- src/views/Explore/components/pro.tsx
- src/views/Explore/components/rankingList.tsx
- src/views/Explore/components/recommend.tsx
> fix: recommend or rank fallback

- src/components/NftSortOrKindList/explore.tsx
- src/components/NftSortOrKindList/index.tsx
> feat: update font weight

- src/i18n/en.json
- src/i18n/zh.json
- src/views/NFT/components/renderer.tsx
> fix: fixed card back color

- README.md
- public/index.html
> chore: change some desc

- src/routes/index.tsx
> chore: change console type

- src/models/holder.ts
- src/models/issuer.ts
- src/views/Issuer/components/address.tsx
- src/views/Issuer/components/appbar.tsx
- src/views/Issuer/components/issuerInfo.tsx
- src/views/NFT/components/footer.tsx
- src/views/NFT/components/holdersList.tsx
- src/views/NFT/components/nftDetail.tsx
> feat: add issuer cover

- src/views/Login/index.tsx
- src/views/NFT/components/renderer.tsx
> Fix: card back

- .github/workflows/prod.yml
> chore: release tag by date

- .github/workflows/prod.yml
> chore: remove tag version ci action

- .github/workflows/build.yml
- src/components/Share/index.tsx
- src/hooks/useHtml2Canvas.ts
> hotfix: fixed share poster save bug on android WeChat

- .github/workflows/prod.yml
- src/components/OrderDrawer/Reselect.tsx
- src/components/OrderDrawer/SelectPayment.tsx
> chore: temp close wechat payment

- src/views/NFT/components/nftDetail.tsx
Fixed blue area clickable, but red area not click.
> fix: fixed issuer name not click on NFT page

- package.json
- src/views/NFT/components/renderer.tsx
- src/views/Redeem/Prize.tsx
- yarn.lock
> fix: fixed image preview center bug

- src/views/Search/hooks/useSearchAPI.ts
> fix: replaced route `push` to `replace`

- src/components/OrderDrawer/Reselect.tsx
- src/components/OrderDrawer/SelectPayment.tsx
- src/components/Share/index.tsx
- src/hooks/useHtml2Canvas.ts
> merge `master` to `develop`

- src/models/red-envelope.ts
- src/views/RedEnvelope/components/records.tsx
- src/views/RedEnvelope/index.tsx
> feat: update new api structure

- .github/workflows/prod.yml
> fix: ci create tag

- .github/workflows/prod.yml
- src/components/OrderDrawer/Reselect.tsx
- src/components/OrderDrawer/SelectPayment.tsx
- src/hooks/useOrder.ts
- src/views/OrderDetail/index.tsx
- src/views/Orders/OrderCard.tsx
> chore remove alipay payment

- src/components/OrderDrawer/Reselect.tsx
- src/components/OrderDrawer/SelectPayment.tsx
- src/hooks/useOrder.ts
> chore: restore alipay payment

- src/hooks/useWechat.ts
- src/models/class-list.ts
- src/models/nft.ts
- src/views/NFT/hooks/useNFTDetailApi.tsx
> feat: add `thumbnail_url` to wx share

- src/components/RainbowBackground/index.tsx
- src/views/Login/index.tsx
- src/views/RedeemResult/index.tsx
> fix: fixed login background height

- .github/workflows/prod.yml
> chore: modify ci tag date

- src/components/PwaGuide/index.tsx
> fix: remove pwa in wechat and imToken

- src/utils/string.ts
- src/utils/url.ts
- src/views/NFT/components/appbar.tsx
- src/views/NFT/components/holdersList.tsx
- src/views/NFT/components/nftTxLogList.tsx
- src/views/NFT/components/renderer.tsx
> hotfix: add preview tid

- src/views/RedEnvelope/components/records.tsx
- src/views/RedEnvelope/index.tsx
> feat: add state opening with error

- package.json
- src/models/class-list.ts
- src/views/NFT/components/footer.tsx
> fix: own token

- package.json
- src/constants/env.ts
- src/hooks/useHistoryBack.ts
- src/views/AddressCollector/index.tsx
- src/views/Claim/index.tsx
- src/views/Flashsigner/index.tsx
- src/views/Transfer/index.tsx
- yarn.lock
> fix: flashsigner issue

- src/views/Profile/DrawerImage.tsx
> fix: expand photo lib button click area

- src/routes/path.ts
- src/routes/routes.ts
- src/service-worker.ts
> feat: new route: cny2022 to `/claim`

- src/components/HiddenBar/index.tsx
- src/hooks/useLite.ts
- src/routes/index.tsx
- src/views/Apps/index.tsx
- src/views/Explore/index.tsx
- src/views/ExploreAll/index.tsx
- src/views/NFTs/index.tsx
> feat: add lite mode by `?is_lite_mode=true`

- src/utils/url.ts
- src/views/RedEnvelope/components/records.tsx
> feat: remove red envelope promotion link origin

- package.json
- src/views/NFT/components/renderer.tsx
- src/views/Redeem/Prize.tsx
- yarn.lock
> chore: update `mibao-ui`

- package.json
- yarn.lock
> chore: bump axios version to 0.21.2

- src/constants/env.ts
> chore: add flashsigner env

- src/views/NFTs/components/appbar.tsx
- src/views/NFTs/components/nftList.tsx
> fix: exclude banned nft in non-holder nft list

- src/views/NFT/components/footer.tsx
- src/views/NFTs/components/appbar.tsx
- src/views/NFTs/components/nftList.tsx
> fix: own token address

- src/utils/flashsigner.ts
> chore: change dapp logo url

- src/hooks/useWechat.ts
> fix: modify wechat share img path

- src/hooks/useWechat.ts
> merge `develop` to `staging`

- src/index.tsx
https://create-react-app.dev/docs/making-a-progressive-web-app/
> refactor: conservative pwa cache

- .buildpacks
- static.json
> add dokku config

- .vscode/settings.json
- src/hooks/useLite.ts
- src/routes/index.tsx
> fix: is lite mode

- src/hooks/useLite.ts
- src/routes/index.tsx
- src/views/NFTs/index.tsx
> fix: fixed lite mode route

- src/constants/env.ts
- src/views/Transfer/index.tsx
> fix: flashsigner transfer to das address 

- package.json
- src/index.tsx
- yarn.lock
> fix: safari 12 compatibility

- public/manifest.json
- src/index.tsx
> fix: pwa not updated

- src/i18n/en.json
> chore: change flashsigner login desc

- src/components/AlbumPlayer/index.tsx
- src/components/Cd/index.tsx
- src/views/NFT/components/renderer.tsx
> fix: fixed cd cover image layout

- package.json
- yarn.lock
> chore: update flashsigner sdk

- src/hooks/useRedeem.ts
> fix: flashsigner redeem

- src/views/HolderAddress/index.tsx
> fix: fixed holder address page layout

- package.json
- src/views/RedEnvelopeDetail/components/tokenList.tsx
- src/views/SendRedEnvelope/components/nftListDrawer.tsx
- src/views/SendRedEnvelope/hooks/useSendRedEnvelope.tsx
- src/views/SendRedEnvelope/index.tsx
- src/views/ShareRedEnvelope/index.tsx
- yarn.lock
> fix: fixed layout and route bug

- src/components/NftSortOrKindList/index.tsx
> fix: fix sometime the tab can't click 

- src/utils/error.ts
- src/views/RedEnvelope/index.tsx
> fix: fixed red-envelope asynchronous operation

- public/manifest.json
- src/apis/ServerWalletAPI.ts
- src/hooks/useAccount.ts
- src/i18n/en.json
- src/i18n/zh.json
- src/views/AddressCollector/index.tsx
- src/views/Claim/index.tsx
- src/views/NFTs/card.tsx
- src/views/NFTs/components/nftList.tsx
> fix: metamask issue

- public/manifest.json
- src/components/Share/components/posters/holder.tsx
> fix: fixed share holder poster

- public/manifest.json
- src/components/AddressBar/index.tsx
- src/utils/unipass.ts
- src/views/NFTs/card.tsx
- src/views/NFTs/components/nftList.tsx
> fix: wrong display address

- public/manifest.json
- src/i18n/en.json
- src/i18n/zh.json
- src/views/Transfer/index.tsx
> refactor: display transfer error code

- public/manifest.json
- src/apis/ServerWalletAPI.ts
- src/hooks/useIsCotaCellReady.tsx
- src/i18n/en.json
- src/i18n/zh.json
- src/models/query.ts
- src/models/transactions.ts
- src/views/NFT/components/footer.tsx
- src/views/Transfer/index.tsx
> feat: detect cota cell status

- src/apis/ServerWalletAPI.ts
- src/components/NftSortOrKindList/explore.tsx
- src/components/NftSortOrKindList/follow.tsx
- src/components/NftSortOrKindList/index.tsx
- src/models/api.ts
- src/views/Explore/components/lite.tsx
- src/views/Issuer/components/appbar.tsx
- src/views/Issuer/components/empty.tsx
- src/views/Issuer/components/nftCards.tsx
> feat: remove sale

- .github/workflows/prod.yml
> chore: change release process

- public/manifest.json
> chore(release): v2.1.0

- src/views/NFT/components/renderer.tsx
> fix: scale the skeleton

- src/routes/index.tsx
修复 iOS 15.0 Safari 的分享操作有概率导致崩溃问题
> fix: try fixing ios 15.0 crash

- src/index.tsx
修复iOS下有概率flashsigner / unipass 登陆卡住
> fix: uninstall safari service worker

- craco.config.js
- public/manifest.json
- src/hooks/useAccount.ts
- src/service-worker.ts
- src/views/Profile/index.tsx
> refactor: all unipass/metamask api use old address

- public/manifest.json
- src/hooks/useAccount.ts
- src/hooks/useProfile.ts
- src/service-worker.ts
> refactor: change cache key

- src/hooks/useTrack.ts
- src/views/Login/index.tsx
> feat: add flashsigner login track

- public/manifest.json
- src/service-worker.ts
> chore(release): v2.2.3

- src/hooks/useAccount.ts
- src/i18n/en.json
- src/i18n/zh.json
- src/views/Claim/index.tsx
> feat: claim url query

- public/manifest.json
- src/App.tsx
- src/service-worker.ts
> chore(release): v2.3.1

- public/index.html
- public/manifest.json
- src/App.tsx
- src/service-worker.ts
> chore(release): v2.3.2

- public/manifest.json
- src/constants/env.ts
- src/i18n/en.json
- src/i18n/zh.json
- src/service-worker.ts
- src/views/Claim/index.tsx
- src/views/Login/index.tsx
> refactor: show unipass in wechat

- public/manifest.json
- src/hooks/useIsCotaCellReady.tsx
- src/service-worker.ts
> refactor: revert cota warning

- src/models/transactions.ts
- src/views/Transactions/index.tsx
> feat: add tx state rejected

- src/hooks/useIsCotaCellReady.tsx
- src/pw/toPwTransaction.ts
> fix: metamask header deps

- src/hooks/useIsCotaCellReady.tsx
- src/models/transactions.ts
- src/pw/toPwTransaction.ts
- src/views/Transactions/index.tsx
> deploy to staging

- public/manifest.json
- src/hooks/useAccount.ts
- src/hooks/useProfile.ts
- src/service-worker.ts
> fix: unipass pubkey empty

- package.json
- src/components/Intro/index.tsx
- yarn.lock
> feat: add close button for tutorial guide
